name-template: v$RESOLVED_VERSION
tag-template: $RESOLVED_VERSION
version-template: $MAJOR.$MINOR.$PATCH
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
      - enhancement
  patch:
    labels:
      - auto-update
      - patch
      - fix
      - bugfix
      - bug
      - hotfix
  default: minor

template: |
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
